//! Convert SDK Forge's [`ApiModel`] into an [`openapiv3::OpenAPI`] specification.
//!
//! This module is the bridge between SDK Forge's internal representation
//! (populated by the analyzer) and the standard `OpenAPI` v3.0 format. The
//! resulting spec can be serialized to JSON/YAML or fed into code generators
//! like progenitor.

use indexmap::IndexMap;
use openapiv3::{
    APIKeyLocation, Components, Info, MediaType, ObjectType, Operation, Parameter, ParameterData,
    ParameterSchemaOrContent, PathItem, Paths, ReferenceOr, Response, Responses, Schema,
    SchemaData, SchemaKind, SecurityRequirement, SecurityScheme, Server, StatusCode, Tag, Type,
};
use sdk_forge_session::types::{
    ApiKeyLocation as SdkApiKeyLocation, ApiModel, AuthPattern, Endpoint, JsonSchema, ResourceGroup,
};

use crate::error::CodegenError;

/// Convert an [`ApiModel`] into an [`openapiv3::OpenAPI`] document.
///
/// # Errors
///
/// Returns `CodegenError::OpenApiConversion` if the model has no resources
/// or an empty `base_url`.
pub fn api_model_to_openapi(model: &ApiModel) -> Result<openapiv3::OpenAPI, CodegenError> {
    if model.base_url.is_empty() {
        return Err(CodegenError::OpenApiConversion {
            reason: "base_url is empty".to_owned(),
        });
    }

    if model.resources.is_empty() {
        return Err(CodegenError::OpenApiConversion {
            reason: "no resource groups defined".to_owned(),
        });
    }

    let tags = build_tags(&model.resources);
    let paths = build_paths(&model.resources)?;
    let components = build_components(model.auth.as_ref());
    let security = model
        .auth
        .as_ref()
        .map(|_| vec![SecurityRequirement::from([("auth".to_owned(), Vec::new())])]);

    Ok(openapiv3::OpenAPI {
        openapi: "3.0.3".to_owned(),
        info: Info {
            title: title_from_base_url(&model.base_url),
            version: "0.1.0".to_owned(),
            description: Some("Auto-generated by SDK Forge from recorded API traffic.".to_owned()),
            ..Info::default()
        },
        servers: vec![Server {
            url: model.base_url.clone(),
            ..Server::default()
        }],
        paths,
        components: Some(components),
        security,
        tags,
        external_docs: None,
        extensions: IndexMap::default(),
    })
}

/// Serialize an [`openapiv3::OpenAPI`] spec to pretty-printed JSON.
///
/// # Errors
///
/// Returns `CodegenError::OpenApiSerialization` if serde fails.
pub fn openapi_to_json(spec: &openapiv3::OpenAPI) -> Result<String, CodegenError> {
    serde_json::to_string_pretty(spec).map_err(|err| CodegenError::OpenApiSerialization {
        reason: err.to_string(),
    })
}

// ── Helpers ──────────────────────────────────────────────────────────

/// Derive a human-readable title from a base URL.
fn title_from_base_url(base_url: &str) -> String {
    // Try to extract the hostname for a nicer title.
    base_url
        .strip_prefix("https://")
        .or_else(|| base_url.strip_prefix("http://"))
        .and_then(|host| host.split('/').next())
        .map_or_else(|| "Generated API".to_owned(), |host| format!("{host} API"))
}

/// Build [`Tag`] entries from resource groups.
fn build_tags(resources: &[ResourceGroup]) -> Vec<Tag> {
    resources
        .iter()
        .map(|rg| Tag {
            name: rg.name.clone(),
            description: Some(format!("Endpoints under {}", rg.base_path)),
            ..Tag::default()
        })
        .collect()
}

/// Build the [`Paths`] object from all resource groups.
fn build_paths(resources: &[ResourceGroup]) -> Result<Paths, CodegenError> {
    let mut paths: IndexMap<String, ReferenceOr<PathItem>> = IndexMap::new();

    for resource in resources {
        for endpoint in &resource.endpoints {
            let full_path = normalize_path(&resource.base_path, &endpoint.path_template);
            let operation = build_operation(endpoint, &resource.name);

            // Get or create the path item for this path.
            let path_item = paths
                .entry(full_path)
                .or_insert_with(|| ReferenceOr::Item(PathItem::default()));

            if let ReferenceOr::Item(item) = path_item {
                assign_operation(item, &endpoint.method, operation)?;
            }
        }
    }

    Ok(Paths {
        paths,
        extensions: IndexMap::default(),
    })
}

/// Combine resource base path and endpoint path template into a single path.
fn normalize_path(base_path: &str, path_template: &str) -> String {
    let base_trimmed = base_path.trim_end_matches('/');
    if path_template.starts_with('/') {
        format!("{base_trimmed}{path_template}")
    } else {
        format!("{base_trimmed}/{path_template}")
    }
}

/// Build a single [`Operation`] from an [`Endpoint`].
fn build_operation(endpoint: &Endpoint, tag_name: &str) -> Operation {
    let mut parameters: Vec<ReferenceOr<Parameter>> = Vec::new();

    // Path parameters.
    for param in &endpoint.path_params {
        parameters.push(ReferenceOr::Item(Parameter::Path {
            parameter_data: ParameterData {
                name: param.name.clone(),
                description: param.description.clone(),
                required: true,
                deprecated: None,
                format: ParameterSchemaOrContent::Schema(ReferenceOr::Item(param_type_to_schema(
                    &param.param_type,
                ))),
                example: None,
                examples: IndexMap::default(),
                explode: None,
                extensions: IndexMap::default(),
            },
            style: openapiv3::PathStyle::Simple,
        }));
    }

    // Query parameters.
    for param in &endpoint.query_params {
        parameters.push(ReferenceOr::Item(Parameter::Query {
            parameter_data: ParameterData {
                name: param.name.clone(),
                description: param.description.clone(),
                required: param.required,
                deprecated: None,
                format: ParameterSchemaOrContent::Schema(ReferenceOr::Item(param_type_to_schema(
                    &param.param_type,
                ))),
                example: None,
                examples: IndexMap::default(),
                explode: None,
                extensions: IndexMap::default(),
            },
            allow_reserved: false,
            style: openapiv3::QueryStyle::Form,
            allow_empty_value: None,
        }));
    }

    // Request body.
    let request_body = endpoint.request_schema.as_ref().map(|schema| {
        let converted = json_schema_to_openapi(schema);
        ReferenceOr::Item(openapiv3::RequestBody {
            content: IndexMap::from([(
                "application/json".to_owned(),
                MediaType {
                    schema: Some(ReferenceOr::Item(converted)),
                    ..MediaType::default()
                },
            )]),
            required: true,
            ..openapiv3::RequestBody::default()
        })
    });

    // Response.
    let response_content = endpoint.response_schema.as_ref().map(|schema| {
        let converted = json_schema_to_openapi(schema);
        MediaType {
            schema: Some(ReferenceOr::Item(converted)),
            ..MediaType::default()
        }
    });

    let ok_response = Response {
        description: "Successful response".to_owned(),
        content: response_content.map_or_else(IndexMap::default, |mt| {
            IndexMap::from([("application/json".to_owned(), mt)])
        }),
        ..Response::default()
    };

    let mut responses_map: IndexMap<StatusCode, ReferenceOr<Response>> = IndexMap::new();
    responses_map.insert(StatusCode::Code(200), ReferenceOr::Item(ok_response));

    let operation_id = build_operation_id(tag_name, &endpoint.method, &endpoint.path_template);

    // Security: if endpoint requires auth, reference the global scheme.
    let security = if endpoint.requires_auth {
        Some(vec![SecurityRequirement::from([(
            "auth".to_owned(),
            Vec::new(),
        )])])
    } else {
        // Empty array means "no auth required" (overrides global security).
        Some(Vec::new())
    };

    Operation {
        tags: vec![tag_name.to_owned()],
        summary: Some(endpoint.description.clone()),
        description: None,
        operation_id: Some(operation_id),
        parameters,
        request_body,
        responses: Responses {
            responses: responses_map,
            ..Responses::default()
        },
        security,
        ..Operation::default()
    }
}

/// Assign an [`Operation`] to the correct HTTP method slot on a [`PathItem`].
fn assign_operation(
    item: &mut PathItem,
    method: &str,
    operation: Operation,
) -> Result<(), CodegenError> {
    match method.to_ascii_uppercase().as_str() {
        "GET" => item.get = Some(operation),
        "POST" => item.post = Some(operation),
        "PUT" => item.put = Some(operation),
        "PATCH" => item.patch = Some(operation),
        "DELETE" => item.delete = Some(operation),
        "HEAD" => item.head = Some(operation),
        "OPTIONS" => item.options = Some(operation),
        "TRACE" => item.trace = Some(operation),
        other => {
            return Err(CodegenError::OpenApiConversion {
                reason: format!("unsupported HTTP method: {other}"),
            });
        }
    }
    Ok(())
}

/// Build an `operation_id` from the tag, method, and path template.
///
/// Example: `("Users", "GET", "/users/{id}")` produces `"users_get_by_id"`.
fn build_operation_id(tag: &str, method: &str, path_template: &str) -> String {
    let tag_part = tag.to_ascii_lowercase();
    let method_part = method.to_ascii_lowercase();

    // Convert path segments into a readable suffix.
    let path_part: String = path_template
        .split('/')
        .filter(|seg| !seg.is_empty())
        .map(|seg| {
            if seg.starts_with('{') && seg.ends_with('}') {
                let inner_len = seg.len().saturating_sub(2);
                let inner = seg.get(1..seg.len().saturating_sub(1)).unwrap_or("id");
                if inner_len == 0 {
                    "id".to_owned()
                } else {
                    format!("by_{inner}")
                }
            } else {
                seg.to_owned()
            }
        })
        .collect::<Vec<_>>()
        .join("_");

    if path_part.is_empty() {
        format!("{tag_part}_{method_part}")
    } else {
        format!("{tag_part}_{method_part}_{path_part}")
    }
}

/// Convert a param type string (e.g., "string", "integer") into a simple [`Schema`].
fn param_type_to_schema(param_type: &str) -> Schema {
    let kind = match param_type {
        "integer" | "int" => SchemaKind::Type(Type::Integer(openapiv3::IntegerType::default())),
        "number" | "float" | "double" => {
            SchemaKind::Type(Type::Number(openapiv3::NumberType::default()))
        }
        "boolean" | "bool" => SchemaKind::Type(Type::Boolean(openapiv3::BooleanType::default())),
        _ => SchemaKind::Type(Type::String(openapiv3::StringType::default())),
    };

    Schema {
        schema_data: SchemaData::default(),
        schema_kind: kind,
    }
}

/// Convert our [`JsonSchema`] to an [`openapiv3::Schema`].
fn json_schema_to_openapi(schema: &JsonSchema) -> Schema {
    let kind = match schema {
        JsonSchema::Object {
            properties,
            required,
        } => {
            let props = properties
                .iter()
                .map(|(name, child)| {
                    let child_schema = json_schema_to_openapi(child);
                    (name.clone(), ReferenceOr::boxed_item(child_schema))
                })
                .collect::<IndexMap<String, ReferenceOr<Box<Schema>>>>();

            SchemaKind::Type(Type::Object(ObjectType {
                properties: props,
                required: required.clone(),
                additional_properties: None,
                min_properties: None,
                max_properties: None,
            }))
        }
        JsonSchema::Array { items } => {
            let items_schema = json_schema_to_openapi(items);
            SchemaKind::Type(Type::Array(openapiv3::ArrayType {
                items: Some(ReferenceOr::boxed_item(items_schema)),
                min_items: None,
                max_items: None,
                unique_items: false,
            }))
        }
        JsonSchema::String { format } => SchemaKind::Type(Type::String(openapiv3::StringType {
            format: format_string_to_variant(format.as_deref()),
            ..openapiv3::StringType::default()
        })),
        JsonSchema::Integer => SchemaKind::Type(Type::Integer(openapiv3::IntegerType::default())),
        JsonSchema::Number => SchemaKind::Type(Type::Number(openapiv3::NumberType::default())),
        JsonSchema::Boolean => SchemaKind::Type(Type::Boolean(openapiv3::BooleanType::default())),
        JsonSchema::Null => {
            // OpenAPI v3.0 has no null type; represent as nullable string.
            SchemaKind::Type(Type::String(openapiv3::StringType::default()))
        }
    };

    let nullable = matches!(schema, JsonSchema::Null);

    Schema {
        schema_data: SchemaData {
            nullable,
            ..SchemaData::default()
        },
        schema_kind: kind,
    }
}

/// Map a format string (like "date-time") to the openapiv3 `VariantOrUnknownOrEmpty`.
fn format_string_to_variant(
    format: Option<&str>,
) -> openapiv3::VariantOrUnknownOrEmpty<openapiv3::StringFormat> {
    match format {
        Some("date") => openapiv3::VariantOrUnknownOrEmpty::Item(openapiv3::StringFormat::Date),
        Some("date-time") => {
            openapiv3::VariantOrUnknownOrEmpty::Item(openapiv3::StringFormat::DateTime)
        }
        Some("password") => {
            openapiv3::VariantOrUnknownOrEmpty::Item(openapiv3::StringFormat::Password)
        }
        Some("byte") => openapiv3::VariantOrUnknownOrEmpty::Item(openapiv3::StringFormat::Byte),
        Some("binary") => openapiv3::VariantOrUnknownOrEmpty::Item(openapiv3::StringFormat::Binary),
        Some(other) => openapiv3::VariantOrUnknownOrEmpty::Unknown(other.to_owned()),
        None => openapiv3::VariantOrUnknownOrEmpty::Empty,
    }
}

/// Build [`Components`] with security schemes derived from the [`AuthPattern`].
fn build_components(auth: Option<&AuthPattern>) -> Components {
    let mut security_schemes: IndexMap<String, ReferenceOr<SecurityScheme>> = IndexMap::new();

    if let Some(pattern) = auth {
        let scheme = auth_pattern_to_security_scheme(pattern);
        security_schemes.insert("auth".to_owned(), ReferenceOr::Item(scheme));
    }

    Components {
        security_schemes,
        ..Components::default()
    }
}

/// Convert an [`AuthPattern`] into an [`openapiv3::SecurityScheme`].
fn auth_pattern_to_security_scheme(pattern: &AuthPattern) -> SecurityScheme {
    match pattern {
        AuthPattern::BearerToken => SecurityScheme::HTTP {
            scheme: "bearer".to_owned(),
            bearer_format: Some("JWT".to_owned()),
            description: Some("Bearer token authentication".to_owned()),
            extensions: IndexMap::default(),
        },
        AuthPattern::ApiKey { location, name } => {
            let api_key_location = match location {
                SdkApiKeyLocation::Header => APIKeyLocation::Header,
                SdkApiKeyLocation::Query => APIKeyLocation::Query,
            };
            SecurityScheme::APIKey {
                location: api_key_location,
                name: name.clone(),
                description: Some("API key authentication".to_owned()),
                extensions: IndexMap::default(),
            }
        }
        AuthPattern::Cookie { cookie_name } => SecurityScheme::APIKey {
            location: APIKeyLocation::Cookie,
            name: cookie_name.clone(),
            description: Some("Cookie-based authentication".to_owned()),
            extensions: IndexMap::default(),
        },
        AuthPattern::BasicAuth => SecurityScheme::HTTP {
            scheme: "basic".to_owned(),
            bearer_format: None,
            description: Some("HTTP Basic authentication".to_owned()),
            extensions: IndexMap::default(),
        },
    }
}

#[cfg(test)]
mod tests {
    #[allow(clippy::wildcard_imports)]
    use super::*;
    use std::collections::HashMap;

    use pretty_assertions::assert_eq;
    use sdk_forge_session::types::{PathParam, QueryParam};

    /// Helper to build a minimal [`ApiModel`] for testing.
    fn sample_api_model() -> ApiModel {
        ApiModel {
            base_url: "https://api.example.com".to_owned(),
            auth: Some(AuthPattern::BearerToken),
            resources: vec![ResourceGroup {
                name: "Users".to_owned(),
                base_path: "/api/v1/users".to_owned(),
                endpoints: vec![
                    Endpoint {
                        method: "GET".to_owned(),
                        path_template: "/".to_owned(),
                        description: "List all users".to_owned(),
                        request_schema: None,
                        response_schema: Some(JsonSchema::Array {
                            items: Box::new(JsonSchema::Object {
                                properties: HashMap::from([
                                    ("id".to_owned(), JsonSchema::Integer),
                                    ("name".to_owned(), JsonSchema::String { format: None }),
                                ]),
                                required: vec!["id".to_owned(), "name".to_owned()],
                            }),
                        }),
                        requires_auth: true,
                        path_params: vec![],
                        query_params: vec![QueryParam {
                            name: "page".to_owned(),
                            param_type: "integer".to_owned(),
                            required: false,
                            description: Some("Page number".to_owned()),
                        }],
                    },
                    Endpoint {
                        method: "GET".to_owned(),
                        path_template: "/{id}".to_owned(),
                        description: "Get a user by ID".to_owned(),
                        request_schema: None,
                        response_schema: Some(JsonSchema::Object {
                            properties: HashMap::from([
                                ("id".to_owned(), JsonSchema::Integer),
                                ("name".to_owned(), JsonSchema::String { format: None }),
                                (
                                    "email".to_owned(),
                                    JsonSchema::String {
                                        format: Some("email".to_owned()),
                                    },
                                ),
                            ]),
                            required: vec!["id".to_owned(), "name".to_owned(), "email".to_owned()],
                        }),
                        requires_auth: true,
                        path_params: vec![PathParam {
                            name: "id".to_owned(),
                            param_type: "integer".to_owned(),
                            description: Some("User ID".to_owned()),
                        }],
                        query_params: vec![],
                    },
                    Endpoint {
                        method: "POST".to_owned(),
                        path_template: "/".to_owned(),
                        description: "Create a new user".to_owned(),
                        request_schema: Some(JsonSchema::Object {
                            properties: HashMap::from([
                                ("name".to_owned(), JsonSchema::String { format: None }),
                                (
                                    "email".to_owned(),
                                    JsonSchema::String {
                                        format: Some("email".to_owned()),
                                    },
                                ),
                            ]),
                            required: vec!["name".to_owned(), "email".to_owned()],
                        }),
                        response_schema: Some(JsonSchema::Object {
                            properties: HashMap::from([("id".to_owned(), JsonSchema::Integer)]),
                            required: vec!["id".to_owned()],
                        }),
                        requires_auth: true,
                        path_params: vec![],
                        query_params: vec![],
                    },
                ],
            }],
            pagination: None,
        }
    }

    #[test]
    fn test_basic_conversion() {
        let model = sample_api_model();
        let spec = api_model_to_openapi(&model);
        assert!(spec.is_ok(), "conversion should succeed");

        let spec_val = spec.unwrap_or_default();
        assert_eq!(spec_val.openapi, "3.0.3", "should use OpenAPI v3.0.3");
        assert_eq!(spec_val.info.title, "api.example.com API");
        assert_eq!(spec_val.servers.len(), 1, "should have one server");
    }

    #[test]
    fn test_empty_base_url_fails() {
        let model = ApiModel {
            base_url: String::new(),
            auth: None,
            resources: vec![ResourceGroup {
                name: "Test".to_owned(),
                base_path: "/test".to_owned(),
                endpoints: vec![],
            }],
            pagination: None,
        };
        let result = api_model_to_openapi(&model);
        assert!(result.is_err(), "empty base_url should fail");
    }

    #[test]
    fn test_no_resources_fails() {
        let model = ApiModel {
            base_url: "https://api.example.com".to_owned(),
            auth: None,
            resources: vec![],
            pagination: None,
        };
        let result = api_model_to_openapi(&model);
        assert!(result.is_err(), "no resources should fail");
    }

    #[test]
    fn test_tags_match_resources() {
        let model = sample_api_model();
        let spec_val = api_model_to_openapi(&model).unwrap_or_default();
        assert_eq!(spec_val.tags.len(), 1, "should have one tag");
        assert_eq!(
            spec_val.tags.first().map(|t| t.name.as_str()),
            Some("Users")
        );
    }

    #[test]
    fn test_paths_generated() {
        let model = sample_api_model();
        let spec_val = api_model_to_openapi(&model).unwrap_or_default();

        // Two paths: /api/v1/users/ and /api/v1/users/{id}.
        assert_eq!(spec_val.paths.paths.len(), 2, "should have two path items");
        assert!(
            spec_val.paths.paths.contains_key("/api/v1/users/"),
            "should contain /api/v1/users/"
        );
        assert!(
            spec_val.paths.paths.contains_key("/api/v1/users/{id}"),
            "should contain /api/v1/users/{{id}}"
        );
    }

    #[test]
    fn test_operations_on_path() {
        let model = sample_api_model();
        let spec_val = api_model_to_openapi(&model).unwrap_or_default();

        // /api/v1/users/ should have GET and POST.
        let path_item = spec_val.paths.paths.get("/api/v1/users/");
        assert!(path_item.is_some(), "path should exist");

        if let Some(ReferenceOr::Item(item)) = path_item {
            assert!(item.get.is_some(), "GET should be present");
            assert!(item.post.is_some(), "POST should be present");
            assert!(item.put.is_none(), "PUT should not be present");
        }
    }

    #[test]
    fn test_bearer_auth_security_scheme() {
        let model = sample_api_model();
        let spec_val = api_model_to_openapi(&model).unwrap_or_default();

        let components = spec_val.components.as_ref();
        assert!(components.is_some(), "components should exist");

        let default_components = Components::default();
        let schemes = &components.unwrap_or(&default_components).security_schemes;
        assert!(
            schemes.contains_key("auth"),
            "should have 'auth' security scheme"
        );
    }

    #[test]
    fn test_api_key_auth() {
        let scheme = auth_pattern_to_security_scheme(&AuthPattern::ApiKey {
            location: SdkApiKeyLocation::Header,
            name: "X-API-Key".to_owned(),
        });

        assert!(
            matches!(
                scheme,
                SecurityScheme::APIKey {
                    location: APIKeyLocation::Header,
                    ..
                }
            ),
            "should be an API key in header"
        );
    }

    #[test]
    fn test_cookie_auth() {
        let scheme = auth_pattern_to_security_scheme(&AuthPattern::Cookie {
            cookie_name: "session".to_owned(),
        });

        assert!(
            matches!(
                scheme,
                SecurityScheme::APIKey {
                    location: APIKeyLocation::Cookie,
                    ..
                }
            ),
            "cookie auth should map to API key in cookie"
        );
    }

    #[test]
    fn test_basic_auth() {
        let scheme = auth_pattern_to_security_scheme(&AuthPattern::BasicAuth);
        assert!(
            matches!(
                scheme,
                SecurityScheme::HTTP {
                    scheme: ref s,
                    ..
                } if s == "basic"
            ),
            "should be HTTP basic"
        );
    }

    #[test]
    fn test_json_schema_string_conversion() {
        let result = json_schema_to_openapi(&JsonSchema::String {
            format: Some("date-time".to_owned()),
        });
        assert!(
            matches!(
                result.schema_kind,
                SchemaKind::Type(Type::String(openapiv3::StringType {
                    format: openapiv3::VariantOrUnknownOrEmpty::Item(
                        openapiv3::StringFormat::DateTime
                    ),
                    ..
                }))
            ),
            "should convert date-time format"
        );
    }

    #[test]
    fn test_json_schema_nested_object() {
        let schema = JsonSchema::Object {
            properties: HashMap::from([
                ("name".to_owned(), JsonSchema::String { format: None }),
                ("age".to_owned(), JsonSchema::Integer),
                ("active".to_owned(), JsonSchema::Boolean),
            ]),
            required: vec!["name".to_owned()],
        };

        let result = json_schema_to_openapi(&schema);
        if let SchemaKind::Type(Type::Object(obj)) = &result.schema_kind {
            assert_eq!(obj.properties.len(), 3, "should have 3 properties");
            assert_eq!(obj.required, vec!["name".to_owned()]);
        } else {
            panic!("expected object schema");
        }
    }

    #[test]
    fn test_json_schema_array_conversion() {
        let schema = JsonSchema::Array {
            items: Box::new(JsonSchema::Integer),
        };

        let result = json_schema_to_openapi(&schema);
        assert!(
            matches!(result.schema_kind, SchemaKind::Type(Type::Array(_))),
            "should be an array"
        );
    }

    #[test]
    fn test_json_schema_null_becomes_nullable() {
        let result = json_schema_to_openapi(&JsonSchema::Null);
        assert!(result.schema_data.nullable, "null should be nullable");
    }

    #[test]
    fn test_operation_id_generation() {
        assert_eq!(
            build_operation_id("Users", "GET", "/"),
            "users_get",
            "root path"
        );
        assert_eq!(
            build_operation_id("Users", "GET", "/{id}"),
            "users_get_by_id",
            "param path"
        );
        assert_eq!(
            build_operation_id("Posts", "POST", "/comments"),
            "posts_post_comments",
            "nested path"
        );
    }

    #[test]
    fn test_title_from_base_url() {
        assert_eq!(
            title_from_base_url("https://api.example.com"),
            "api.example.com API"
        );
        assert_eq!(
            title_from_base_url("https://api.example.com/v1"),
            "api.example.com API"
        );
        assert_eq!(title_from_base_url("invalid"), "Generated API");
    }

    #[test]
    fn test_normalize_path() {
        assert_eq!(normalize_path("/api/v1", "/users"), "/api/v1/users");
        assert_eq!(normalize_path("/api/v1/", "/users"), "/api/v1/users");
        assert_eq!(normalize_path("/api/v1", "users"), "/api/v1/users");
    }

    #[test]
    fn test_unsupported_method_fails() {
        let mut item = PathItem::default();
        let result = assign_operation(&mut item, "INVALID", Operation::default());
        assert!(result.is_err(), "unsupported method should fail");
    }

    #[test]
    fn test_openapi_to_json_roundtrip() {
        let model = sample_api_model();
        let spec_val = api_model_to_openapi(&model).unwrap_or_default();
        let json = openapi_to_json(&spec_val);
        assert!(json.is_ok(), "should serialize to JSON");

        let json_str = json.unwrap_or_default();
        assert!(
            json_str.contains("\"openapi\""),
            "JSON should contain openapi field"
        );
        assert!(
            json_str.contains("api.example.com"),
            "JSON should contain base URL"
        );
    }

    #[test]
    fn test_endpoint_without_auth_has_empty_security() {
        let endpoint = Endpoint {
            method: "GET".to_owned(),
            path_template: "/public".to_owned(),
            description: "Public endpoint".to_owned(),
            request_schema: None,
            response_schema: None,
            requires_auth: false,
            path_params: vec![],
            query_params: vec![],
        };

        let operation = build_operation(&endpoint, "Public");
        assert_eq!(
            operation.security,
            Some(Vec::new()),
            "no-auth endpoint should have empty security array"
        );
    }

    #[test]
    fn test_param_type_to_schema() {
        let int_schema = param_type_to_schema("integer");
        assert!(
            matches!(int_schema.schema_kind, SchemaKind::Type(Type::Integer(_))),
            "integer type"
        );

        let bool_schema = param_type_to_schema("boolean");
        assert!(
            matches!(bool_schema.schema_kind, SchemaKind::Type(Type::Boolean(_))),
            "boolean type"
        );

        let str_schema = param_type_to_schema("unknown");
        assert!(
            matches!(str_schema.schema_kind, SchemaKind::Type(Type::String(_))),
            "unknown type should default to string"
        );
    }
}
